language: ruby
rvm: 2.1.1
env:
  global:
  - GIT_COMMITTER_NAME="Okumura Takahiro"
  - GIT_COMMITTER_EMAIL="hfm.garden@gmail.com"
  - GIT_AUTHOR_NAME="Okumura Takahiro"
  - GIT_AUTHOR_EMAIL="hfm.garden@gmail.com"
  - secure: VMBN/OH9XmAbnwNQ3q7QqeDoD8gEPziaMt1B1slb6iV8dFebdRHOntcH6e71U3dq7r4bav2gdjW+PP6KzT297XkQLhkxuplYX71SwL6LiLcsQNB/Ql8gdFukEUEqK1eohdzqHnZ3Htd2r/b5Euj1KkQmQw3osyiShnzb/CvTj0w=
before_script:
  - git clone --quiet https://github.com/tacahilo/tacahilo.github.com.git build
  - pushd build
  - git checkout -b gh-pages
  - popd
script:
  - bundle exec nanoc compile
after_success:
  - cd build
  - git add -A
  - git commit -m 'Update'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://github.com/tacahilo/tacahilo.github.com.git gh-pages 2> /dev/null'
